version: '3.4'
services:

# ************ DATABASES ************
  book-db: 
    image: postgres
    restart: "always"
    environment:
        POSTGRES_PASSWORD: postgres066252
        POSTGRES_USER: postgres
        POSTGRES_DB: bookdb
    ports:
      - "5434:5432"
    #volumes:
    #  - app-volumne:/var/lib/postgresql/data
    networks:
      - microservice-network
  cambio-db: 
    image: postgres
    restart: "always"
    environment:
        POSTGRES_PASSWORD: postgres066252
        POSTGRES_USER: postgres
        POSTGRES_DB: cambiodb
    ports:
      - "5435:5432"
    #volumes:
    #  - app-volumne:/var/lib/postgresql/data
    networks:
      - microservice-network
networks:
  microservice-network:
    driver: bridge
volumes:
  app-volumne: #
