server:
  port: 8100
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 2
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      default:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book_db
    username: postgres
    password: postgres066252
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  flyway:
    url: jdbc:postgresql://localhost:5432/book_db
    user: postgres
    password: postgres066252