server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book_db
    username: postgres
    password: postgres066252
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  flyway:
    url: jdbc:postgresql://localhost:5432/book_db
    user: postgres
    password: postgres066252