server:
  port: 8888

spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EduardoSantAna1313/microservices/
          default-label: main
          search-paths:
            - 'greeting-service-config/greeting-service*'